let porsche = new Marca("porsche");
let ferrari = new Marca("ferrari");
let ford = new Marca("ford");
let seat = new Marca("seat");
let renault = new Marca("renault");

porsche.anyadirModelo("718 Boxster")
porsche.anyadirModelo("18 Cayman")
porsche.anyadirModelo("911")
porsche.anyadirModelo("918 Spyder")
porsche.anyadirModelo("Cayenne")
porsche.anyadirModelo("Cayman")
porsche.anyadirModelo("Macan")
porsche.anyadirModelo("Panamera")

ferrari.anyadirModelo("458")
ferrari.anyadirModelo("488")
ferrari.anyadirModelo("California T")
ferrari.anyadirModelo("F12 Berlinetta")
ferrari.anyadirModelo("FF")
ferrari.anyadirModelo("Laferrari")
ferrari.anyadirModelo("Portofino")

ford.anyadirModelo("B-max")
ford.anyadirModelo("C-max")
ford.anyadirModelo("exosport")
ford.anyadirModelo("edge")
ford.anyadirModelo("fiesta")
ford.anyadirModelo("focus")
ford.anyadirModelo("galaxy")
ford.anyadirModelo("ka+")
ford.anyadirModelo("kuga")
ford.anyadirModelo("mondeo")
ford.anyadirModelo("mustang")
ford.anyadirModelo("ranger")
ford.anyadirModelo("s-max")
ford.anyadirModelo("tourneo connect")
ford.anyadirModelo("tourneo custom")

seat.anyadirModelo("alhambra")
seat.anyadirModelo("altea")
seat.anyadirModelo("arona")
seat.anyadirModelo("ateca")
seat.anyadirModelo("ibiza")
seat.anyadirModelo("leon")
seat.anyadirModelo("mii")
seat.anyadirModelo("toledo")

renault.anyadirModelo("captur")
renault.anyadirModelo("clio")
renault.anyadirModelo("espace")
renault.anyadirModelo("fluence")
renault.anyadirModelo("kadjar")
renault.anyadirModelo("kangoo")
renault.anyadirModelo("koleos")
renault.anyadirModelo("laguna")
renault.anyadirModelo("mégane")
renault.anyadirModelo("scénic")
renault.anyadirModelo("talismán")
renault.anyadirModelo("trafic")
renault.anyadirModelo("twingo")
renault.anyadirModelo("twizy")
renault.anyadirModelo("zoe")